[package]
name = "proj"
version = "0.1.0"
authors = ["david sharp <david.m.sharp@wellsfargo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
